# Email Notification Functions for ContractLink AI
# Handles transactional emails for password resets, admin notifications, etc.

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def send_email(to_email, subject, html_content, text_content=None):
    """
    Send an email using SMTP configuration from environment variables
    
    Args:
        to_email: Recipient email address
        subject: Email subject line
        html_content: HTML email body
        text_content: Plain text email body (optional, falls back to HTML)
    
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    try:
        # Get SMTP settings from environment
        smtp_host = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
        smtp_port = int(os.getenv('EMAIL_PORT', '587'))
        smtp_user = os.getenv('EMAIL_USER')
        smtp_password = os.getenv('EMAIL_PASSWORD')
        from_email = os.getenv('EMAIL_FROM', smtp_user)
        from_name = os.getenv('EMAIL_FROM_NAME', 'ContractLink AI')
        
        if not smtp_user or not smtp_password:
            print("Warning: EMAIL_USER or EMAIL_PASSWORD not configured. Email not sent.")
            return False
        
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"{from_name} <{from_email}>"
        msg['To'] = to_email
        
        # Add plain text and HTML parts
        if text_content:
            part1 = MIMEText(text_content, 'plain')
            msg.attach(part1)
        
        part2 = MIMEText(html_content, 'html')
        msg.attach(part2)
        
        # Send email
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
        
        return True
        
    except Exception as e:
        print(f"Error sending email to {to_email}: {e}")
        return False


def send_password_reset_email(user_email, new_password, admin_email):
    """
    Send password reset notification to user
    
    Args:
        user_email: User's email address
        new_password: Temporary password generated by admin
        admin_email: Admin who performed the reset
    """
    subject = "Your ContractLink AI Password Has Been Reset"
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
            .content {{ background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }}
            .password-box {{ background: white; border: 2px solid #667eea; padding: 20px; margin: 20px 0; border-radius: 8px; text-align: center; }}
            .password {{ font-size: 24px; font-weight: bold; color: #667eea; letter-spacing: 2px; }}
            .button {{ display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
            .footer {{ text-align: center; color: #666; font-size: 12px; margin-top: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Password Reset</h1>
            </div>
            <div class="content">
                <p>Hello,</p>
                <p>Your ContractLink AI password has been reset by an administrator.</p>
                
                <div class="password-box">
                    <p style="margin: 0; color: #666; font-size: 14px;">Your new temporary password:</p>
                    <p class="password">{new_password}</p>
                </div>
                
                <p><strong>⚠️ Important:</strong></p>
                <ul>
                    <li>Please change this password immediately after logging in</li>
                    <li>Go to your profile settings to update your password</li>
                    <li>Do not share this password with anyone</li>
                </ul>
                
                <p style="text-align: center;">
                    <a href="{os.getenv('APP_URL', 'https://contractlink.ai')}/signin" class="button">
                        Sign In Now
                    </a>
                </p>
                
                <p>If you did not request this password reset, please contact support immediately.</p>
                
                <p>Best regards,<br>The ContractLink AI Team</p>
            </div>
            <div class="footer">
                <p>This is an automated message. Please do not reply to this email.</p>
                <p>Reset performed by: {admin_email} at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    text_content = f"""
    Password Reset - ContractLink AI
    
    Hello,
    
    Your ContractLink AI password has been reset by an administrator.
    
    Your new temporary password: {new_password}
    
    IMPORTANT:
    - Please change this password immediately after logging in
    - Go to your profile settings to update your password
    - Do not share this password with anyone
    
    Sign in at: {os.getenv('APP_URL', 'https://contractlink.ai')}/signin
    
    If you did not request this password reset, please contact support immediately.
    
    Best regards,
    The ContractLink AI Team
    
    Reset performed by: {admin_email} at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    """
    
    return send_email(user_email, subject, html_content, text_content)


def send_admin_consultation_notification(admin_email, user_data):
    """
    Notify admin about new consultation request
    
    Args:
        admin_email: Admin email to notify
        user_data: Dictionary with consultation request details
    """
    subject = f"New Consultation Request from {user_data.get('name', 'Unknown')}"
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
            .content {{ background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }}
            .info-box {{ background: white; border-left: 4px solid #667eea; padding: 15px; margin: 15px 0; }}
            .label {{ font-weight: bold; color: #667eea; }}
            .button {{ display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🔔 New Consultation Request</h1>
            </div>
            <div class="content">
                <p>A new consultation request has been submitted:</p>
                
                <div class="info-box">
                    <p><span class="label">Name:</span> {user_data.get('name', 'N/A')}</p>
                    <p><span class="label">Email:</span> {user_data.get('email', 'N/A')}</p>
                    <p><span class="label">Phone:</span> {user_data.get('phone', 'N/A')}</p>
                    <p><span class="label">Company:</span> {user_data.get('company', 'N/A')}</p>
                    <p><span class="label">Service Level:</span> {user_data.get('service_level', 'N/A')}</p>
                    <p><span class="label">Message:</span><br>{user_data.get('message', 'N/A')}</p>
                </div>
                
                <p><span class="label">Submitted:</span> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                
                <p style="text-align: center;">
                    <a href="{os.getenv('APP_URL', 'https://contractlink.ai')}/admin-enhanced" class="button">
                        View in Admin Panel
                    </a>
                </p>
                
                <p><strong>Next Steps:</strong></p>
                <ul>
                    <li>Review the consultation request details</li>
                    <li>Contact the client within 24 hours</li>
                    <li>Schedule a discovery call if appropriate</li>
                </ul>
            </div>
        </div>
    </body>
    </html>
    """
    
    text_content = f"""
    New Consultation Request - ContractLink AI
    
    A new consultation request has been submitted:
    
    Name: {user_data.get('name', 'N/A')}
    Email: {user_data.get('email', 'N/A')}
    Phone: {user_data.get('phone', 'N/A')}
    Company: {user_data.get('company', 'N/A')}
    Service Level: {user_data.get('service_level', 'N/A')}
    
    Message:
    {user_data.get('message', 'N/A')}
    
    Submitted: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    
    View in admin panel: {os.getenv('APP_URL', 'https://contractlink.ai')}/admin-enhanced
    
    Next Steps:
    - Review the consultation request details
    - Contact the client within 24 hours
    - Schedule a discovery call if appropriate
    """
    
    return send_email(admin_email, subject, html_content, text_content)


def send_proposal_review_notification(admin_emails, proposal_data):
    """
    Notify proposal specialists about new review request
    
    Args:
        admin_emails: List of admin emails to notify
        proposal_data: Dictionary with proposal review details
    """
    subject = f"New Proposal Review Request - {proposal_data.get('contract_title', 'Untitled')[:50]}"
    
    for admin_email in admin_emails:
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
                .content {{ background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }}
                .info-box {{ background: white; border-left: 4px solid #667eea; padding: 15px; margin: 15px 0; }}
                .label {{ font-weight: bold; color: #667eea; }}
                .urgent {{ background: #fff3cd; border-left-color: #ffc107; }}
                .button {{ display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>📝 Proposal Review Request</h1>
                </div>
                <div class="content">
                    <p>A client has requested proposal review assistance:</p>
                    
                    <div class="info-box {('urgent' if proposal_data.get('urgency') == 'high' else '')}">
                        <p><span class="label">Client:</span> {proposal_data.get('client_name', 'N/A')}</p>
                        <p><span class="label">Email:</span> {proposal_data.get('client_email', 'N/A')}</p>
                        <p><span class="label">Contract:</span> {proposal_data.get('contract_title', 'N/A')}</p>
                        <p><span class="label">Due Date:</span> {proposal_data.get('due_date', 'N/A')}</p>
                        <p><span class="label">Urgency:</span> {proposal_data.get('urgency', 'normal').upper()}</p>
                    </div>
                    
                    <p><span class="label">Request Details:</span><br>{proposal_data.get('review_notes', 'No additional notes provided.')}</p>
                    
                    <p style="text-align: center;">
                        <a href="{os.getenv('APP_URL', 'https://contractlink.ai')}/admin-enhanced?section=proposals" class="button">
                            View Proposal Request
                        </a>
                    </p>
                    
                    <p><strong>Action Required:</strong></p>
                    <ul>
                        <li>Review the proposal submission</li>
                        <li>Contact client to schedule review session</li>
                        <li>Provide feedback within 48 hours</li>
                    </ul>
                </div>
            </div>
        </body>
        </html>
        """
        
        send_email(admin_email, subject, html_content)


# Export all notification functions
__all__ = [
    'send_email',
    'send_password_reset_email',
    'send_admin_consultation_notification',
    'send_proposal_review_notification'
]
