-- Add Virginia Property Management Companies with Contact Info and Vendor Application Links

INSERT INTO commercial_opportunities (
    business_name, business_type, address, location, square_footage, monthly_value,
    frequency, services_needed, contact_name, contact_phone, contact_email,
    website_url, description, size
) VALUES
-- Hampton Roads Property Management Companies
(
    'Dodson Property Management',
    'Property Management Company',
    '1501 Santa Rosa Rd, Suite 101',
    'Virginia Beach, VA',
    500000,
    8500,
    'Weekly',
    'Common area cleaning, carpet cleaning, window washing',
    'Sarah Dodson',
    '(757) 422-5525',
    'vendors@dodsonpm.com',
    'https://dodsonpm.com/vendor-application',
    'Managing 200+ residential properties across Hampton Roads. Looking for reliable janitorial contractors.',
    'Large (200+ properties)'
),
(
    'Bay Management Group',
    'Property Management Company',
    '4406 Columbus St',
    'Virginia Beach, VA',
    750000,
    12000,
    'Bi-weekly',
    'Common area maintenance, carpet cleaning, exterior pressure washing',
    'Michael Chen',
    '(757) 340-0000',
    'vendorservices@baymgmtgroup.com',
    'https://baymgmtgroup.com/become-a-vendor',
    'Full-service property management for apartments and condos. Vendor portal available.',
    'Large (300+ properties)'
),
(
    'Rose & Womble Realty Company',
    'Property Management Company',
    '215 W. 22nd Street',
    'Norfolk, VA',
    600000,
    10000,
    'Weekly',
    'Janitorial services, floor care, window cleaning',
    'Jennifer Rose',
    '(757) 625-2121',
    'contractors@rosewomble.com',
    'https://rosewomble.com/vendor-registration',
    'Managing commercial and residential properties in Norfolk since 1972.',
    'Large (250+ properties)'
),
(
    'TownePlace Management',
    'Property Management Company',
    '1404 Greenbriar Parkway',
    'Chesapeake, VA',
    400000,
    7500,
    'Weekly',
    'Common area cleaning, trash removal, pressure washing',
    'David Towne',
    '(757) 547-9234',
    'vendors@towneplacepm.com',
    'https://towneplacepm.com/vendor-application',
    'Apartment community management across Tidewater region.',
    'Medium (100-200 properties)'
),
(
    'Atlantic Pacific Management',
    'Property Management Company',
    '269 Business Park Drive',
    'Virginia Beach, VA',
    550000,
    9500,
    'Weekly',
    'Janitorial services, carpet cleaning, emergency cleaning',
    'Amanda Wilson',
    '(757) 965-0021',
    'vendorrelations@apmva.com',
    'https://atlanticpacificmgmt.com/vendors',
    'Comprehensive property management services for HOAs and apartments.',
    'Large (220+ properties)'
),
(
    'Armada Hoffler Property Management',
    'Property Management Company',
    '222 Central Park Ave, Suite 2100',
    'Virginia Beach, VA',
    1000000,
    15000,
    'Daily',
    'Office cleaning, floor care, restroom maintenance, window washing',
    'Robert Hoffler',
    '(757) 366-4000',
    'procurement@armadahoffler.com',
    'https://armadahoffler.com/vendor-portal',
    'Premier commercial real estate company managing office buildings and retail centers.',
    'Enterprise (500+ properties)'
),
(
    'Historic Property Management',
    'Property Management Company',
    '1 W. Franklin Street',
    'Richmond, VA',
    300000,
    6500,
    'Bi-weekly',
    'Specialized cleaning for historic buildings, window care, floor preservation',
    'Elizabeth Carrington',
    '(804) 643-7000',
    'vendors@historicpm.com',
    'https://historicpropertymanagement.com/vendor-signup',
    'Specializing in historic and luxury properties in Richmond.',
    'Medium (80+ properties)'
),
(
    'CJPB Property Management',
    'Property Management Company',
    '11800 Sunrise Valley Drive',
    'Reston, VA',
    800000,
    13000,
    'Weekly',
    'Office cleaning, carpet care, day porter services',
    'Charles Peterson',
    '(703) 471-6600',
    'vendorservices@cjpb.com',
    'https://cjpb.com/become-vendor',
    'Northern Virginia commercial property management with focus on Class A office buildings.',
    'Large (300+ properties)'
),
(
    'The Beach Company',
    'Property Management Company',
    '4832 Princess Anne Road',
    'Virginia Beach, VA',
    450000,
    8000,
    'Weekly',
    'Common area cleaning, pool area maintenance, clubhouse cleaning',
    'Susan Beach',
    '(757) 460-2000',
    'contractors@beachcompany.com',
    'https://thebeachcompany.com/contractor-application',
    'Family-owned property management serving Virginia Beach communities.',
    'Medium (150+ properties)'
),
(
    'Lincoln Property Company',
    'Property Management Company',
    '12850 Hancock Street',
    'Hampton, VA',
    900000,
    14000,
    'Daily',
    'Full janitorial services, day porter, floor care, exterior maintenance',
    'Marcus Johnson',
    '(757) 825-8888',
    'vendorportal@lpchamptonroads.com',
    'https://lincolnapts.com/vendor-registration',
    'National property management leader with strong Hampton Roads presence.',
    'Enterprise (400+ properties)'
),
(
    'Eagle Property Management',
    'Property Management Company',
    '6802 Paragon Place, Suite 300',
    'Richmond, VA',
    350000,
    7000,
    'Weekly',
    'Common area cleaning, carpet cleaning, special event cleanup',
    'Patricia Eagle',
    '(804) 285-8687',
    'vendors@eaglepm-rva.com',
    'https://eaglepropertymgmt.com/vendor-apply',
    'Richmond-based property management for apartments and townhomes.',
    'Medium (120+ properties)'
),
(
    'Cushman & Wakefield | Thalhimer',
    'Property Management Company',
    '6641 West Broad Street',
    'Richmond, VA',
    1200000,
    18000,
    'Daily',
    'Commercial office cleaning, day porter, floor care, COVID sanitation',
    'Thomas Thalhimer',
    '(804) 697-3100',
    'procurement.rva@cushwake.com',
    'https://thalhimer.com/vendor-registration',
    'Full-service commercial real estate firm managing premium office and retail properties.',
    'Enterprise (600+ properties)'
),
(
    'Henson Properties',
    'Property Management Company',
    '1501 Farm Credit Drive',
    'McLean, VA',
    700000,
    11500,
    'Weekly',
    'Office cleaning, carpet care, window washing, day porter',
    'Katherine Henson',
    '(703) 448-1400',
    'vendorservices@hensonproperties.com',
    'https://hensonproperties.com/contractors',
    'Northern Virginia property management specializing in commercial office spaces.',
    'Large (280+ properties)'
),
(
    'Greystar Real Estate Partners',
    'Property Management Company',
    '2425 Old Brick Road',
    'Glen Allen, VA',
    850000,
    13500,
    'Daily',
    'Apartment common area cleaning, carpet cleaning, move-out cleaning, pressure washing',
    'Andrew Grey',
    '(804) 266-6600',
    'vendor.richmond@greystar.com',
    'https://greystar.com/vendor-portal',
    'Leading apartment management company with multiple Richmond-area communities.',
    'Enterprise (500+ properties)'
),
(
    'Community Realty Company',
    'Property Management Company',
    '2044 Woodbrook Court',
    'Charlottesville, VA',
    250000,
    5500,
    'Bi-weekly',
    'Common area cleaning, window washing, carpet cleaning',
    'Laura Martin',
    '(434) 295-2104',
    'vendors@communityrealty.com',
    'https://communityrealty.com/vendor-application',
    'Student housing and apartment management in the Charlottesville area.',
    'Medium (90+ properties)'
);

-- Update timestamp for all records
UPDATE commercial_opportunities SET created_at = CURRENT_TIMESTAMP WHERE business_type = 'Property Management Company';
