-- ==============================================================
-- ADDITIONAL SUPPLY CONTRACTS - Batch 2
-- Add 14 more contracts to reach 30 total supply opportunities
-- ==============================================================

INSERT INTO supply_contracts (
    title, agency, location, contract_type, product_category, estimated_value, 
    contract_term, bid_deadline, delivery_start, description, requirements, 
    product_list, minimum_order, delivery_frequency, website_url, 
    contact_name, contact_email, contact_phone, is_quick_win, 
    is_small_business_set_aside, status
) VALUES

-- HAMPTON ADDITIONAL
(
    'Window Cleaning Supplies Annual Contract',
    'City of Hampton',
    'Hampton, VA',
    'Annual Supply Contract',
    'Window Cleaning Supplies',
    48000.00,
    '1 year',
    '2025-11-22',
    '2025-12-10',
    'Annual supply of window cleaning products including squeegees, scrapers, poles, and professional-grade cleaners for all city buildings.',
    'Commercial grade equipment. Safety certified extension poles. Streak-free formula cleaners.',
    'Window cleaning solution (concentrate), squeegees (all sizes), scrapers, extension poles (8-24ft), microfiber towels, buckets',
    '$250 minimum',
    'Quarterly + emergency 48hr',
    'https://www.hampton.gov/bids.aspx',
    'Facilities Manager',
    'facilities@hampton.gov',
    '757-727-6100',
    TRUE,
    TRUE,
    'open'
),

(
    'Carpet Cleaning Products Standing Order',
    'Hampton City Schools',
    'Hampton, VA',
    'Standing Order',
    'Carpet Care Products',
    67000.00,
    '2 years',
    '2025-11-26',
    '2025-12-15',
    'Standing order for carpet cleaning chemicals, spot removers, and deodorizers for 15 school buildings.',
    'Low-moisture formulas preferred. Safe for children. No harsh odors.',
    'Carpet shampoo, encapsulation cleaner, spot remover, deodorizer, pre-spray, extraction chemicals',
    '$350 minimum',
    'Quarterly scheduled',
    'https://www.hampton.gov/schools',
    'Maintenance Director',
    'maintenance@hcs.k12.va.us',
    '757-727-2100',
    TRUE,
    TRUE,
    'open'
),

-- NORFOLK ADDITIONAL
(
    'Industrial Degreaser Bulk Purchase',
    'Norfolk Naval Shipyard - Civilian Services',
    'Norfolk, VA',
    'Annual Supply Contract',
    'Cleaning Chemicals',
    185000.00,
    '1 year with 3 renewals',
    '2025-12-03',
    '2026-01-02',
    'Industrial strength degreasers and heavy-duty cleaners for maintenance facilities and workshops.',
    'NSN compliance. Biodegradable formulas preferred. 55-gallon drum pricing.',
    'Industrial degreaser, engine cleaner, parts washer solvent, concrete cleaner, heavy-duty all-purpose cleaner',
    '$1,500 minimum',
    'Monthly bulk delivery',
    'https://www.norfolk.gov/bids.aspx',
    'GSA Contracting',
    'gsa.norfolk@navy.mil',
    '757-396-3000',
    FALSE,
    FALSE,
    'open'
),

(
    'Odor Control Products for City Facilities',
    'City of Norfolk',
    'Norfolk, VA',
    'Blanket Purchase Agreement',
    'Odor Control Products',
    42000.00,
    '6 months with extension',
    '2025-11-19',
    '2025-11-30',
    'BPA for odor eliminators, air fresheners, and enzymatic cleaners for restrooms, locker rooms, and public facilities.',
    'Enzymatic formulas. Long-lasting. No masking fragrances. Eco-friendly.',
    'Enzymatic odor eliminator, urinal screens, air fresheners (automatic & manual), bio-remediation products',
    '$200 minimum',
    'Bi-weekly + emergency',
    'https://www.norfolk.gov/bids.aspx',
    'Procurement Specialist',
    'procurement@norfolk.gov',
    '757-664-4100',
    TRUE,
    TRUE,
    'open'
),

-- VIRGINIA BEACH ADDITIONAL
(
    'Beach & Park Restroom Supplies Contract',
    'Virginia Beach Parks & Recreation',
    'Virginia Beach, VA',
    'Annual Supply Contract',
    'Restroom Supplies',
    210000.00,
    '1 year',
    '2025-12-01',
    '2025-12-20',
    'Complete restroom supply package for 40+ beach and park restroom facilities including oceanfront locations.',
    'Weather-resistant products. High-volume dispensers. Vandal-resistant when possible. Salt-air compatible.',
    'Industrial toilet paper, paper towels, hand soap, air fresheners, trash bags, dispensers (weather-resistant)',
    '$1,000 minimum',
    'Weekly delivery to distribution',
    'https://www.vbgov.com/departments/procurement',
    'Parks Director',
    'parks@vbgov.com',
    '757-385-1100',
    FALSE,
    TRUE,
    'open'
),

(
    'Pressure Washing Chemicals & Equipment',
    'VB Public Works',
    'Virginia Beach, VA',
    'Standing Order',
    'Cleaning Chemicals',
    92000.00,
    '1 year',
    '2025-11-28',
    '2025-12-15',
    'Pressure washing chemicals, degreasers, and equipment for maintaining city sidewalks, buildings, and infrastructure.',
    'Professional grade. Various pressure ratings. Eco-compliant for storm drains.',
    'Concrete cleaner, building wash, degreaser, deck cleaner, mildew remover, pressure washer accessories',
    '$500 minimum',
    'Monthly + emergency',
    'https://www.vbgov.com/departments/procurement',
    'Public Works Supply',
    'pwsupply@vbgov.com',
    '757-385-4650',
    TRUE,
    TRUE,
    'open'
),

-- NEWPORT NEWS ADDITIONAL
(
    'Microfiber Cleaning System Annual Supply',
    'Newport News Public Schools',
    'Newport News, VA',
    'Annual Supply Contract',
    'Janitorial Equipment',
    58000.00,
    '1 year',
    '2025-11-24',
    '2025-12-10',
    'Complete microfiber cleaning system including mops, cloths, frames, and laundering supplies for green cleaning initiative.',
    'Color-coded system. Industrial laundering compatible. Minimum 500 wash cycles.',
    'Microfiber mop heads (all sizes), dust cloths, glass cloths, mop frames, microfiber detergent',
    '$300 minimum',
    'Quarterly + emergency',
    'https://www.nn.k12.va.us/procurement',
    'Green Initiative Coordinator',
    'green@nn.k12.va.us',
    '757-591-4600',
    TRUE,
    TRUE,
    'open'
),

(
    'Restroom Fixture Cleaners & Descalers',
    'City of Newport News',
    'Newport News, VA',
    'Standing Order',
    'Cleaning Chemicals',
    36000.00,
    '1 year',
    '2025-11-21',
    '2025-12-05',
    'Specialized cleaners for restroom fixtures including lime/scale removers, bowl cleaners, and stainless steel polish.',
    'Safe for all plumbing systems. Hard water formula. No acid-based products.',
    'Toilet bowl cleaner, urinal cleaner, descaler, stainless steel polish, fixture brightener, drain maintainer',
    '$200 minimum',
    'Monthly delivery',
    'https://www.nngov.com/procurement',
    'Building Services',
    'building.services@nngov.com',
    '757-926-8800',
    TRUE,
    TRUE,
    'open'
),

-- CHESAPEAKE ADDITIONAL
(
    'Food Service Area Cleaning Supplies',
    'Chesapeake Public Schools - Child Nutrition',
    'Chesapeake, VA',
    'Annual Supply Contract',
    'Food Service Sanitation',
    78000.00,
    '1 year',
    '2025-11-29',
    '2025-12-18',
    'Commercial kitchen and cafeteria cleaning supplies including degreasers, sanitizers, and food-safe cleaners for 45 school kitchens.',
    'NSF certified. Food-safe. Health department approved. No-rinse sanitizers.',
    'Food-safe degreaser, sanitizer (quat-based), oven cleaner, stainless steel cleaner, floor degreaser',
    '$400 minimum',
    'Bi-weekly scheduled',
    'https://www.cpschools.com/procurement',
    'Child Nutrition Services',
    'cns@cpschools.com',
    '757-547-0200',
    TRUE,
    TRUE,
    'open'
),

-- PORTSMOUTH ADDITIONAL
(
    'HVAC Coil Cleaners & Maintenance Chemicals',
    'Portsmouth City Schools',
    'Portsmouth, VA',
    'Standing Order',
    'Maintenance Chemicals',
    44000.00,
    '1 year',
    '2025-11-23',
    '2025-12-08',
    'HVAC coil cleaners, condensate drain treatments, and air handler cleaning products for school facility maintenance.',
    'Non-corrosive. EPA compliant. Safe for aluminum and copper coils.',
    'Coil cleaner (foaming & spray), condensate drain treatment, air handler cleaner, filter spray',
    '$250 minimum',
    'Quarterly + emergency 72hr',
    'https://www.portsmouthva.gov/procurement',
    'Facilities Maintenance',
    'facilities@portsmouthva.gov',
    '757-393-8750',
    TRUE,
    TRUE,
    'open'
),

-- SUFFOLK ADDITIONAL
(
    'Vehicle Fleet Cleaning Products',
    'City of Suffolk - Fleet Services',
    'Suffolk, VA',
    'Annual Supply Contract',
    'Auto Care Products',
    52000.00,
    '1 year',
    '2025-11-27',
    '2025-12-15',
    'Complete line of vehicle cleaning products for city fleet including police, fire, and public works vehicles.',
    'Professional auto detailing grade. Salt-removal formula. Paint-safe.',
    'Vehicle wash soap, wheel cleaner, tire shine, interior cleaner, glass cleaner, degreaser, wax',
    '$300 minimum',
    'Monthly scheduled',
    'https://www.suffolk.va.us/departments/procurement',
    'Fleet Manager',
    'fleet@suffolk.va.us',
    '757-514-7660',
    TRUE,
    TRUE,
    'open'
),

-- WILLIAMSBURG/JAMES CITY ADDITIONAL
(
    'Historic Preservation Cleaning Products',
    'Colonial Williamsburg Foundation',
    'Williamsburg, VA',
    'Specialized Contract',
    'Specialty Cleaning Products',
    95000.00,
    '2 years',
    '2025-12-05',
    '2026-01-10',
    'Specialized pH-neutral and heritage-safe cleaning products for historic buildings, artifacts, and furniture.',
    'Conservation-grade products only. pH 7-8 range. No VOCs. Archival safe.',
    'pH-neutral cleaner, wood soap (museum grade), brass/silver polish, stone cleaner, fabric cleaner (heritage-safe)',
    '$500 minimum',
    'Monthly + conservation emergency',
    'https://www.colonialwilliamsburg.org/procurement',
    'Conservation Services',
    'conservation@cwf.org',
    '757-220-7200',
    FALSE,
    TRUE,
    'open'
),

-- REGIONAL OPPORTUNITIES
(
    'Gym Equipment Sanitizing System',
    'YMCA South Hampton Roads',
    'Multiple Locations, VA',
    'Annual Supply Contract',
    'Athletic Facility Supplies',
    68000.00,
    '1 year',
    '2025-11-30',
    '2025-12-20',
    'Touchless sanitizing system and refills for fitness equipment across 8 Hampton Roads YMCA locations.',
    'Touchless dispensers. Fast-drying. Non-corrosive on equipment. Pleasant scent.',
    'Equipment sanitizer (spray & wipes), touchless dispensers, hand sanitizer, spray bottles',
    '$400 minimum',
    'Bi-weekly to each location',
    'https://www.peninsulaymca.org/contact',
    'Operations Director',
    'operations@ymcashr.org',
    '757-838-8885',
    TRUE,
    FALSE,
    'open'
),

(
    'Marine-Grade Cleaning Products',
    'Hampton Roads Sanitation District',
    'Multiple Locations, VA',
    'Annual Supply Contract',
    'Industrial Cleaning Products',
    156000.00,
    '2 years',
    '2025-12-08',
    '2026-01-15',
    'Marine-grade and industrial cleaning products for water treatment facilities including anti-corrosion cleaners.',
    'Corrosion-resistant. EPA wastewater compliant. High-strength formulas. Bulk 55-gal drums.',
    'Industrial degreaser, concrete cleaner, tank cleaner, anti-corrosion coating, safety showers chemicals',
    '$1,200 minimum',
    'Monthly bulk delivery',
    'https://www.hrsd.com/procurement',
    'Procurement Department',
    'procurement@hrsd.com',
    '757-460-7003',
    FALSE,
    FALSE,
    'open'
);

-- Verification
SELECT 'Batch 2 Complete!' as status;
SELECT COUNT(*) as total_supply_contracts FROM supply_contracts;
SELECT COUNT(*) as quick_wins FROM supply_contracts WHERE is_quick_win = TRUE;
SELECT COUNT(*) as small_business FROM supply_contracts WHERE is_small_business_set_aside = TRUE;

-- Summary by product category
SELECT product_category, COUNT(*) as count 
FROM supply_contracts 
GROUP BY product_category 
ORDER BY count DESC;
