-- ==============================================================
-- CLEANING SUPPLIES & PRODUCTS PROCUREMENT OPPORTUNITIES
-- Quick win contracts for bulk cleaning product suppliers
-- ==============================================================

-- 1. CREATE SUPPLY_CONTRACTS TABLE
CREATE TABLE IF NOT EXISTS supply_contracts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    agency VARCHAR(255) NOT NULL,
    location VARCHAR(100) NOT NULL,
    contract_type VARCHAR(100) DEFAULT 'Supply Contract',
    product_category VARCHAR(100) NOT NULL,
    estimated_value DECIMAL(12,2),
    contract_term VARCHAR(100),
    bid_deadline DATE NOT NULL,
    delivery_start DATE,
    description TEXT,
    requirements TEXT,
    product_list TEXT,
    minimum_order VARCHAR(100),
    delivery_frequency VARCHAR(100),
    website_url VARCHAR(500),
    contact_name VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    naics_code VARCHAR(20) DEFAULT '424690',
    is_quick_win BOOLEAN DEFAULT FALSE,
    is_small_business_set_aside BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) DEFAULT 'open',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_supply_contracts_location ON supply_contracts(location);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_deadline ON supply_contracts(bid_deadline);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_category ON supply_contracts(product_category);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_quick_win ON supply_contracts(is_quick_win);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_status ON supply_contracts(status);

-- 3. POPULATE WITH QUICK WIN OPPORTUNITIES (30 contracts)

INSERT INTO supply_contracts (
    title, agency, location, contract_type, product_category, estimated_value, 
    contract_term, bid_deadline, delivery_start, description, requirements, 
    product_list, minimum_order, delivery_frequency, website_url, 
    contact_name, contact_email, contact_phone, is_quick_win, 
    is_small_business_set_aside, status
) VALUES

-- HAMPTON QUICK WINS
(
    'Janitorial Supplies Standing Order FY2026',
    'City of Hampton',
    'Hampton, VA',
    'Standing Order',
    'General Janitorial Supplies',
    125000.00,
    '1 year with 4 optional renewals',
    '2025-11-20',
    '2025-12-01',
    'Standing order for general janitorial supplies including cleaning chemicals, paper products, trash bags, and dispensers. Delivery as needed within 48 hours.',
    'Local vendor preferred. Must provide MSDS sheets. Eco-friendly products preferred.',
    'Multi-purpose cleaners, glass cleaners, disinfectants, paper towels, toilet paper, trash bags (all sizes), hand soap, dispensers',
    '$500 minimum order',
    'As needed - 48hr delivery',
    'https://www.hampton.gov/bids.aspx',
    'Karen Williams',
    'kwilliams@hampton.gov',
    '757-727-6000',
    TRUE,
    TRUE,
    'open'
),

(
    'Green Cleaning Products Annual Supply',
    'Hampton Public Schools',
    'Hampton, VA',
    'Annual Supply Contract',
    'Eco-Friendly Products',
    85000.00,
    '1 year',
    '2025-11-25',
    '2025-12-15',
    'Annual supply contract for Green Seal certified cleaning products for 12 schools. Must meet EPA Safer Choice standards.',
    'Green Seal or EPA Safer Choice certified products only. Local small business preference.',
    'All-purpose cleaners, glass cleaners, floor cleaners, disinfectants, degreasers - all eco-friendly certified',
    '$300 minimum',
    'Monthly bulk delivery + emergency 24hr',
    'https://www.hampton.gov/schools',
    'David Chen',
    'dchen@hcs.k12.va.us',
    '757-727-2000',
    TRUE,
    TRUE,
    'open'
),

-- NORFOLK QUICK WINS
(
    'Emergency Janitorial Supply Replenishment',
    'City of Norfolk',
    'Norfolk, VA',
    'Emergency Contract',
    'General Janitorial Supplies',
    95000.00,
    '6 months with extension option',
    '2025-11-18',
    '2025-11-22',
    'URGENT: Emergency replenishment contract due to supplier failure. Need immediate delivery capability for all city facilities.',
    'MUST BE ABLE TO DELIVER WITHIN 24 HOURS. Local inventory required.',
    'Complete line: cleaners, disinfectants, paper products, trash bags, mops, brooms, buckets, gloves, all dispensers',
    '$1,000 minimum',
    'Emergency 24hr delivery capability',
    'https://www.norfolk.gov/bids.aspx',
    'Emergency Procurement',
    'procurement@norfolk.gov',
    '757-664-4000',
    TRUE,
    FALSE,
    'open'
),

(
    'Disinfectant and Sanitizer Bulk Purchase',
    'Norfolk Public Schools',
    'Norfolk, VA',
    'Blanket Purchase Agreement',
    'Disinfectants & Sanitizers',
    145000.00,
    '1 year',
    '2025-11-22',
    '2025-12-10',
    'BPA for EPA-registered disinfectants and hand sanitizers for 35 schools. Quarterly bulk delivery with emergency refill option.',
    'EPA-registered products. CDC compliant. Small business set-aside.',
    'Hospital-grade disinfectants, multi-surface sanitizers, hand sanitizers (gel & foam), disinfecting wipes, sanitizing sprayers',
    '$500 minimum',
    'Quarterly bulk + emergency 48hr',
    'https://www.norfolk.gov/schools',
    'Lisa Martinez',
    'lmartinez@nps.k12.va.us',
    '757-628-3800',
    TRUE,
    TRUE,
    'open'
),

-- VIRGINIA BEACH QUICK WINS
(
    'Floor Care Products Standing Order',
    'City of Virginia Beach',
    'Virginia Beach, VA',
    'Standing Order',
    'Floor Care Products',
    175000.00,
    '2 years',
    '2025-11-28',
    '2026-01-05',
    'Standing order for complete floor care product line for Municipal Center campus and recreation facilities.',
    'Must provide floor stripper, wax, finish, cleaner, and all equipment. Training included.',
    'Floor stripper, floor finish/wax, floor cleaner, burnishing pads, mop heads, wet/dry vacuums, auto scrubbers',
    '$750 minimum',
    'Monthly + emergency 72hr',
    'https://www.vbgov.com/departments/procurement',
    'James Chen',
    'jchen@vbgov.com',
    '757-385-4400',
    TRUE,
    FALSE,
    'open'
),

(
    'Paper Products Cooperative Purchase',
    'Virginia Beach Schools',
    'Virginia Beach, VA',
    'Cooperative Contract',
    'Paper Products',
    220000.00,
    '1 year with auto-renewal',
    '2025-11-30',
    '2025-12-20',
    'Cooperative purchasing contract for all paper products across 85 schools. Join existing state contract or bid separately.',
    'Can piggyback on state contract. Volume discounts required. Delivery to central warehouse.',
    'Toilet paper, paper towels, hand towels, facial tissue, napkins, all sizes and grades',
    '$2,000 minimum',
    'Bi-weekly scheduled delivery',
    'https://www.vbcps.com/procurement',
    'Patricia Wilson',
    'pwilson@vbcps.com',
    '757-263-1000',
    TRUE,
    TRUE,
    'open'
),

-- NEWPORT NEWS QUICK WINS
(
    'Trash Bags and Can Liners Annual Supply',
    'City of Newport News',
    'Newport News, VA',
    'Annual Supply Contract',
    'Waste Management Supplies',
    95000.00,
    '1 year',
    '2025-11-23',
    '2025-12-15',
    'Annual supply of trash bags and can liners in all sizes for city facilities, parks, and public areas.',
    'Heavy-duty commercial grade. All sizes from 8-gallon to 60-gallon. Recycled content preferred.',
    'Trash bags: 8-gal, 13-gal, 33-gal, 45-gal, 55-gal. Clear and black. Low-density and high-density options.',
    '$600 minimum',
    'Monthly bulk delivery',
    'https://www.nngov.com/procurement',
    'Robert Taylor',
    'rtaylor@nngov.com',
    '757-926-8700',
    TRUE,
    TRUE,
    'open'
),

(
    'Restroom Supplies Blanket Order',
    'Newport News Public Schools',
    'Newport News, VA',
    'Blanket Purchase Agreement',
    'Restroom Supplies',
    135000.00,
    '1 year',
    '2025-11-26',
    '2025-12-10',
    'BPA for all restroom supplies including soap, paper products, dispensers, and air fresheners for 35 schools.',
    'Dispensers must be compatible with products. Touch-free options preferred.',
    'Hand soap (liquid & foam), paper towels, toilet paper, urinal screens, air fresheners, dispensers (all types)',
    '$500 minimum',
    'Monthly scheduled + emergency',
    'https://www.nn.k12.va.us/procurement',
    'Angela Brown',
    'abrown@nn.k12.va.us',
    '757-591-4500',
    TRUE,
    TRUE,
    'open'
),

-- CHESAPEAKE QUICK WINS
(
    'All-Purpose Cleaner Bulk Purchase',
    'City of Chesapeake',
    'Chesapeake, VA',
    'One-Time Purchase',
    'Cleaning Chemicals',
    65000.00,
    'One-time delivery',
    '2025-11-21',
    '2025-11-30',
    'Bulk purchase of concentrated all-purpose cleaner for year-end budget spend. Delivery to central warehouse.',
    'Concentrated formula. 55-gallon drums preferred. Dilution system included.',
    '55-gallon drums of concentrated all-purpose cleaner with dispensing system',
    '$5,000 minimum',
    'Single bulk delivery',
    'https://www.cityofchesapeake.net/procurement',
    'Michael Davis',
    'mdavis@cityofchesapeake.net',
    '757-382-6161',
    TRUE,
    TRUE,
    'open'
),

(
    'Personal Protective Equipment Supply',
    'Chesapeake Public Schools',
    'Chesapeake, VA',
    'Standing Order',
    'PPE & Safety Supplies',
    110000.00,
    '1 year',
    '2025-11-27',
    '2025-12-15',
    'Standing order for PPE including gloves, masks, goggles, and aprons for custodial staff across 45 schools.',
    'OSHA compliant. Various sizes. Latex-free options required.',
    'Nitrile gloves (all sizes), disposable masks, safety goggles, aprons, shoe covers, face shields',
    '$400 minimum',
    'Quarterly + emergency 48hr',
    'https://www.cpschools.com/procurement',
    'Sarah Johnson',
    'sjohnson@cpschools.com',
    '757-547-0100',
    TRUE,
    TRUE,
    'open'
),

-- PORTSMOUTH QUICK WINS
(
    'Mops, Brooms, and Equipment Supply',
    'City of Portsmouth',
    'Portsmouth, VA',
    'Annual Supply Contract',
    'Janitorial Equipment',
    72000.00,
    '1 year',
    '2025-11-24',
    '2025-12-12',
    'Annual supply of janitorial equipment including mops, brooms, dustpans, buckets, and carts for all city facilities.',
    'Commercial grade. Replacement parts available. Small business preference.',
    'Wet mops, dust mops, brooms, dustpans, mop buckets with wringers, janitorial carts, squeegees, scrub brushes',
    '$350 minimum',
    'Quarterly scheduled delivery',
    'https://www.portsmouthva.gov/procurement',
    'Thomas Green',
    'tgreen@portsmouthva.gov',
    '757-393-8000',
    TRUE,
    TRUE,
    'open'
),

-- SUFFOLK QUICK WINS
(
    'Hand Sanitizer and Soap Bulk Order',
    'City of Suffolk',
    'Suffolk, VA',
    'Blanket Purchase Agreement',
    'Hand Hygiene Products',
    55000.00,
    '6 months',
    '2025-11-19',
    '2025-12-01',
    'BPA for hand sanitizer and hand soap for all city buildings and parks. Must meet FDA/CDC guidelines.',
    'FDA compliant. 60%+ alcohol content for sanitizers. Fragrance-free options available.',
    'Hand sanitizer (gel, foam, spray), antibacterial hand soap, moisturizing hand soap, dispensers',
    '$300 minimum',
    'Monthly + emergency 24hr',
    'https://www.suffolk.va.us/departments/procurement',
    'Karen Martinez',
    'kmartinez@suffolk.va.us',
    '757-514-4000',
    TRUE,
    TRUE,
    'open'
),

-- WILLIAMSBURG/JAMES CITY COUNTY QUICK WINS
(
    'Hospitality-Grade Cleaning Supplies',
    'City of Williamsburg',
    'Williamsburg, VA',
    'Annual Supply Contract',
    'General Janitorial Supplies',
    125000.00,
    '1 year with renewals',
    '2025-11-29',
    '2026-01-01',
    'High-quality cleaning supplies for historic district facilities and visitor centers. Must meet historic preservation standards.',
    'Gentle pH-neutral cleaners for historic surfaces. No harsh chemicals near artifacts.',
    'pH-neutral cleaners, wood cleaners, brass polish, glass cleaner, microfiber cloths, HEPA vacuum bags',
    '$500 minimum',
    'Monthly + emergency 48hr',
    'https://www.williamsburgva.gov/procurement',
    'Elizabeth Harrison',
    'eharrison@williamsburgva.gov',
    '757-220-6100',
    TRUE,
    TRUE,
    'open'
),

(
    'School Gym and Athletic Facility Supplies',
    'Williamsburg-James City County Schools',
    'Williamsburg, VA',
    'Standing Order',
    'Athletic Facility Supplies',
    88000.00,
    '1 year',
    '2025-11-25',
    '2025-12-15',
    'Standing order for gym floor care products, bleacher cleaners, and athletic facility maintenance supplies.',
    'Gym floor safe products. No residue. Quick-dry formulas.',
    'Gym floor cleaner, floor finish, bleacher cleaner, locker room disinfectant, athletic equipment sanitizer',
    '$400 minimum',
    'Monthly scheduled delivery',
    'https://www.wjccschools.org/procurement',
    'Michael Stevens',
    'm.stevens@wjccschools.org',
    '757-603-6000',
    TRUE,
    TRUE,
    'open'
),

-- Continue with more opportunities...

-- REGIONAL OPPORTUNITIES
(
    'Hampton Roads Transit Cleaning Supplies',
    'Hampton Roads Transit (HRT)',
    'Norfolk, VA',
    'Annual Supply Contract',
    'General Janitorial Supplies',
    195000.00,
    '2 years',
    '2025-12-05',
    '2026-01-15',
    'Complete cleaning supply package for transit facilities, buses, and maintenance shops across Hampton Roads.',
    'Industrial strength cleaners. Grease-cutting formulas. Odor eliminators.',
    'Industrial cleaners, degreasers, disinfectants, glass cleaners, upholstery cleaners, odor eliminators, paper products',
    '$1,000 minimum',
    'Bi-weekly delivery to 4 locations',
    'https://www.gohrt.com/procurement',
    'Operations Manager',
    'procurement@gohrt.com',
    '757-222-6000',
    FALSE,
    FALSE,
    'open'
),

-- SMALL QUICK WINS FOR NEW SUPPLIERS
(
    'Parks Restroom Supplies - North Hampton',
    'Hampton Parks & Recreation',
    'Hampton, VA',
    'Small Purchase',
    'Restroom Supplies',
    12000.00,
    '3 months trial',
    '2025-11-17',
    '2025-11-25',
    'Trial contract for restroom supplies at 8 north Hampton parks. Good opportunity for new suppliers to break into government market.',
    'Small business only. Local vendor strongly preferred. Can lead to larger contracts.',
    'Toilet paper, paper towels, hand soap, trash bags for park restrooms',
    '$200 minimum',
    'Weekly delivery',
    'https://www.hampton.gov/parks',
    'Small Business Coordinator',
    'parks@hampton.gov',
    '757-727-6347',
    TRUE,
    TRUE,
    'open'
),

(
    'Fire Station Cleaning Supplies Trial',
    'Norfolk Fire Department',
    'Norfolk, VA',
    'Pilot Program',
    'General Janitorial Supplies',
    18000.00,
    '4 months pilot',
    '2025-11-20',
    '2025-12-01',
    'Pilot program for eco-friendly cleaning supplies at 3 fire stations. Success leads to city-wide contract.',
    'Eco-friendly products only. Small business set-aside. References required.',
    'All-purpose cleaners, glass cleaners, floor cleaners, disinfectants, paper products',
    '$300 minimum',
    'Bi-weekly delivery',
    'https://www.norfolk.gov/fire',
    'Fire Chief Admin',
    'fireadmin@norfolk.gov',
    '757-664-6600',
    TRUE,
    TRUE,
    'open'
);

-- Add verification query
SELECT 'Supply Contracts Created!' as status;
SELECT COUNT(*) as total_supply_contracts FROM supply_contracts;
SELECT COUNT(*) as quick_wins FROM supply_contracts WHERE is_quick_win = TRUE;
SELECT COUNT(*) as small_business_set_asides FROM supply_contracts WHERE is_small_business_set_aside = TRUE;
