-- Virginia Colleges and Universities Procurement Data
-- Insert sample educational institution procurement opportunities

INSERT INTO educational_contracts (institution_name, institution_type, city, county, contact_name, contact_title, contact_email, contact_phone, department, opportunity_title, description, category, estimated_value, contract_term, bid_deadline, start_date, requirements, submission_method, website_url, status) VALUES

-- Hampton University
('Hampton University', 'Private University', 'Hampton', 'Hampton City', 'Michael Johnson', 'Procurement Director', 'procurement@hamptonu.edu', '(757) 727-5000', 'Facilities Management', 'Campus-Wide Janitorial Services', 'Seeking qualified cleaning contractors for comprehensive janitorial services across campus including academic buildings, dormitories, athletic facilities, and administrative offices. Green cleaning products preferred.', 'Cleaning & Janitorial', 850000.00, '3 years', '2025-12-15', '2026-01-01', 'Must have experience with educational facilities, provide eco-friendly products, background checks for all staff, proof of insurance ($2M liability), references from similar institutions', 'Electronic via Bonfire', 'https://hamptonu.edu/procurement', 'open'),

-- Christopher Newport University
('Christopher Newport University', 'Public University', 'Newport News', 'Newport News City', 'Sarah Williams', 'Director of Purchasing', 'procurement@cnu.edu', '(757) 594-7000', 'Physical Plant', 'Residence Hall Cleaning Services', 'Annual contract for daily cleaning services in 12 residence halls housing approximately 4,000 students. Must maintain high standards and respond to emergency cleaning needs.', 'Cleaning & Janitorial', 420000.00, '1 year with renewal', '2025-11-30', '2026-01-15', 'Virginia State Corporation Commission registration, Criminal background checks, $1M liability insurance, Green Seal certified products preferred', 'Email submission', 'https://cnu.edu/purchasing', 'open'),

-- Norfolk State University
('Norfolk State University', 'Public University', 'Norfolk', 'Norfolk City', 'James Thompson', 'Procurement Manager', 'jthomp@nsu.edu', '(757) 823-8600', 'Facilities Services', 'Academic Building Custodial Services', 'Custodial services for 15 academic buildings totaling 800,000 square feet. Services include daily cleaning, floor care, window washing, and special event setup.', 'Cleaning & Janitorial', 680000.00, '2 years', '2025-12-20', '2026-02-01', 'Minimum 5 years experience, ISSA CIMS certification preferred, EPA Safer Choice products, staff training documentation, OSHA compliance', 'eVA procurement system', 'https://eva.virginia.gov', 'open'),

-- Old Dominion University
('Old Dominion University', 'Public University', 'Norfolk', 'Norfolk City', 'Patricia Martinez', 'Senior Buyer', 'pmartine@odu.edu', '(757) 683-3000', 'Facilities Management', 'Athletic Facilities Cleaning Contract', 'Cleaning and maintenance services for athletic complex including Ted Constant Convocation Center, Kornblau Field, and training facilities. Event-based cleaning required.', 'Cleaning & Janitorial', 520000.00, '2 years with option', '2025-12-01', '2026-01-01', 'Experience with large venue cleaning, flexible scheduling for events, rapid response capability, $3M liability insurance, bloodborne pathogen training', 'Electronic submission', 'https://odu.edu/procurement', 'open'),

-- Virginia Wesleyan University
('Virginia Wesleyan University', 'Private University', 'Virginia Beach', 'Virginia Beach City', 'Robert Chen', 'Business Services Director', 'rchen@vwu.edu', '(757) 455-3200', 'Campus Operations', 'Campus Custodial Services', 'Complete custodial services for 300-acre campus including academic buildings, residence halls, dining facilities, and recreation center. Approximately 200,000 sq ft.', 'Cleaning & Janitorial', 380000.00, '3 years', '2025-11-25', '2026-01-01', 'Small campus experience, personalized service, eco-friendly products, background checks, $1M insurance, local references', 'Mail or email', 'https://vwu.edu/business-office', 'open'),

-- Tidewater Community College
('Tidewater Community College', 'Community College', 'Norfolk', 'Norfolk City', 'Linda Harrison', 'Purchasing Agent', 'lharrison@tcc.edu', '(757) 822-1122', 'Facilities', 'Multi-Campus Cleaning Services', 'Janitorial services for 4 campuses (Norfolk, Virginia Beach, Chesapeake, Portsmouth). Daytime and evening cleaning required. Total 500,000 sq ft.', 'Cleaning & Janitorial', 620000.00, '1 year renewable', '2025-12-10', '2026-01-15', 'Multi-site management experience, quality control systems, green cleaning certification, diverse workforce goals, competitive pricing', 'eVA system', 'https://eva.virginia.gov', 'open'),

-- Thomas Nelson Community College
('Thomas Nelson Community College', 'Community College', 'Hampton', 'Hampton City', 'David Rodriguez', 'Procurement Specialist', 'drodriguez@tncc.edu', '(757) 825-2700', 'Physical Plant', 'General Custodial Services', 'Daily custodial services for Hampton and Historic Triangle campuses. Includes classrooms, labs, offices, common areas, and restrooms. Green cleaning emphasis.', 'Cleaning & Janitorial', 290000.00, '2 years', '2025-12-05', '2026-01-01', 'Community college experience, EPA registered products, staff screening, detailed quality plan, emergency response capability', 'Email submission', 'https://tncc.edu/purchasing', 'open'),

-- Eastern Virginia Medical School
('Eastern Virginia Medical School', 'Medical School', 'Norfolk', 'Norfolk City', 'Dr. Amanda Foster', 'Facilities Director', 'fostera@evms.edu', '(757) 446-5600', 'Environmental Services', 'Medical Facility Cleaning Services', 'Specialized cleaning services for medical school facilities including research labs, clinical areas, classrooms, and administrative spaces. Healthcare-grade disinfection required.', 'Cleaning & Janitorial', 480000.00, '1 year with renewal', '2025-11-28', '2026-01-01', 'Healthcare facility experience required, BBP training, OSHA bloodborne pathogen compliance, medical-grade disinfectants, EPA registered products, HIPAA awareness', 'Formal RFP process', 'https://evms.edu/procurement', 'open'),

-- William & Mary
('College of William & Mary', 'Public University', 'Williamsburg', 'Williamsburg City', 'Elizabeth Cooper', 'Procurement Services Manager', 'ecooper@wm.edu', '(757) 221-4000', 'Facilities Management', 'Historic Campus Cleaning Services', 'Custodial services for historic campus including colonial-era buildings. Special care required for historic structures. Approximately 600,000 sq ft.', 'Cleaning & Janitorial', 720000.00, '3 years', '2025-12-18', '2026-02-01', 'Historic building experience, gentle cleaning methods, preservation awareness, advanced training, $2M insurance, detailed work plans', 'eVA procurement', 'https://eva.virginia.gov', 'open'),

-- Regent University
('Regent University', 'Private University', 'Virginia Beach', 'Virginia Beach City', 'Mark Stevens', 'Director of Operations', 'markste@regent.edu', '(757) 352-4127', 'Campus Services', 'University-Wide Custodial Contract', 'Comprehensive cleaning services for academic buildings, student center, library, chapel, and residence halls. Christian environment with professional service standards.', 'Cleaning & Janitorial', 540000.00, '2 years', '2025-12-12', '2026-01-15', 'Values-based company preferred, professional appearance standards, flexible scheduling, eco-friendly products, competitive pricing, local presence', 'Email or mail', 'https://regent.edu/facilities', 'open');

-- Add more opportunities for floor care, window cleaning, and special services
INSERT INTO educational_contracts (institution_name, institution_type, city, county, contact_name, contact_title, contact_email, contact_phone, department, opportunity_title, description, category, estimated_value, contract_term, bid_deadline, start_date, requirements, submission_method, website_url, status) VALUES

('Hampton University', 'Private University', 'Hampton', 'Hampton City', 'Michael Johnson', 'Procurement Director', 'procurement@hamptonu.edu', '(757) 727-5000', 'Facilities Management', 'Floor Care and Maintenance Services', 'Annual floor stripping, waxing, buffing, and carpet cleaning services for all campus buildings. Summer deep cleaning included.', 'Floor Care & Maintenance', 125000.00, '1 year renewable', '2025-11-30', '2026-01-01', 'Commercial floor care equipment, trained technicians, eco-friendly products, insurance coverage', 'Electronic submission', 'https://hamptonu.edu/procurement', 'open'),

('Old Dominion University', 'Public University', 'Norfolk', 'Norfolk City', 'Patricia Martinez', 'Senior Buyer', 'pmartine@odu.edu', '(757) 683-3000', 'Facilities Management', 'Window Cleaning Services', 'Exterior and interior window cleaning for campus buildings including high-rise residence halls and multi-story academic buildings.', 'Window Cleaning', 85000.00, '2 years', '2025-12-15', '2026-01-01', 'High-rise experience, safety equipment and training, insurance, fall protection systems', 'eVA system', 'https://eva.virginia.gov', 'open'),

('Christopher Newport University', 'Public University', 'Newport News', 'Newport News City', 'Sarah Williams', 'Director of Purchasing', 'procurement@cnu.edu', '(757) 594-7000', 'Physical Plant', 'Green Cleaning Products Supply', 'Annual supply contract for eco-friendly cleaning products, paper products, and janitorial supplies campus-wide. Green Seal or EcoLogo certified required.', 'Janitorial Supplies', 95000.00, '1 year', '2025-11-28', '2026-01-01', 'Green certifications, bulk pricing, reliable delivery, product training', 'Email submission', 'https://cnu.edu/purchasing', 'open');
