-- Industry Days and Events Data for Virginia Contractors
-- Insert upcoming industry days and networking events

INSERT INTO industry_days (event_title, organizer, organizer_type, event_date, event_time, location, city, venue_name, event_type, description, target_audience, registration_required, registration_deadline, registration_link, contact_name, contact_email, contact_phone, topics, is_virtual, virtual_link, status) VALUES

('Virginia Procurement Conference 2025', 'Virginia Department of General Services', 'State Agency', '2025-12-05', '8:00 AM - 5:00 PM', '600 East Main Street, Richmond, VA 23219', 'Richmond', 'Richmond Convention Center', 'Conference', 'Annual conference bringing together state agencies, local governments, and contractors. Learn about upcoming procurement opportunities, networking sessions, and one-on-one meetings with procurement officers.', 'Small businesses, contractors, vendors', TRUE, '2025-11-25', 'https://dgs.virginia.gov/procurement-conference', 'Jennifer Williams', 'jennifer.williams@dgs.virginia.gov', '(804) 786-3311', 'State procurement processes, eVA system training, small business programs, upcoming opportunities, networking', FALSE, NULL, 'upcoming'),

('Hampton Roads Small Business Expo', 'Hampton Roads Chamber of Commerce', 'Business Organization', '2025-11-20', '9:00 AM - 4:00 PM', '500 Main Street, Norfolk, VA 23510', 'Norfolk', 'Norfolk Waterside Marriott', 'Industry Day', 'Showcase for small businesses to connect with government agencies and prime contractors. Features procurement workshops, matchmaking sessions, and exhibitor booths.', 'Small businesses, contractors, service providers', TRUE, '2025-11-15', 'https://hrchamber.com/expo', 'Michael Thompson', 'mthompson@hrchamber.com', '(757) 622-2312', 'Government contracting, bid preparation, small business certifications, networking', FALSE, NULL, 'upcoming'),

('Military Installation Contractor Day', 'Naval Facilities Engineering Command', 'Federal Agency', '2025-12-12', '10:00 AM - 3:00 PM', 'Naval Station Norfolk, Norfolk, VA', 'Norfolk', 'Naval Station Norfolk Base Chapel', 'Industry Day', 'Meet with base facilities managers and learn about upcoming maintenance and repair contracts for Hampton Roads military installations. Security clearance or base pass required.', 'Contractors, maintenance companies, cleaning services', TRUE, '2025-12-05', 'https://navfac.navy.mil/industry-day', 'Commander Sarah Davis', 'sarah.davis@navy.mil', '(757) 322-8400', 'Base maintenance contracts, facilities services, janitorial services, grounds maintenance', FALSE, NULL, 'upcoming'),

('Educational Facilities Management Summit', 'Virginia Association of School Business Officials', 'Professional Association', '2025-11-18', '8:30 AM - 4:00 PM', 'Williamsburg Lodge, Williamsburg, VA', 'Williamsburg', 'Williamsburg Lodge', 'Conference', 'Annual summit for K-12 and higher education facilities managers. Discuss best practices, new technologies, and upcoming procurement opportunities for schools and universities.', 'Contractors, facilities services, education vendors', TRUE, '2025-11-10', 'https://vasbo.org/summit', 'Dr. Robert Martinez', 'rmartinez@vasbo.org', '(804) 565-4200', 'School facilities maintenance, green cleaning, energy efficiency, procurement processes', FALSE, NULL, 'upcoming'),

('City of Virginia Beach Vendor Showcase', 'City of Virginia Beach Purchasing', 'Local Government', '2025-11-22', '1:00 PM - 5:00 PM', '2401 Courthouse Drive, Virginia Beach, VA', 'Virginia Beach', 'Municipal Center Building 1', 'Vendor Forum', 'Meet city department heads and learn about FY2026 procurement opportunities. Q&A sessions with purchasing staff and one-on-one networking time.', 'Local vendors, contractors, service providers', TRUE, '2025-11-18', 'https://vbgov.com/vendor-showcase', 'Angela Foster', 'afoster@vbgov.com', '(757) 385-4131', 'City procurement, annual contracts, emergency services, facilities maintenance', FALSE, NULL, 'upcoming'),

('Newport News Shipbuilding Supplier Diversity Day', 'Huntington Ingalls Industries', 'Private Sector', '2025-12-08', '9:00 AM - 2:00 PM', '4101 Washington Avenue, Newport News, VA', 'Newport News', 'Newport News Shipbuilding', 'Industry Day', 'Connect with shipyard prime contractors and learn about subcontracting opportunities. Focus on facilities services, janitorial, grounds maintenance, and general services.', 'Small businesses, diverse suppliers, service contractors', TRUE, '2025-12-01', 'https://nns.huntingtoningalls.com/suppliers', 'David Chen', 'david.chen@hii-nns.com', '(757) 380-2000', 'Subcontracting opportunities, supplier diversity, facilities services, vendor registration', FALSE, NULL, 'upcoming'),

('Virtual Green Cleaning Certification Workshop', 'Virginia Green Business Network', 'Non-Profit', '2025-11-15', '10:00 AM - 12:00 PM', 'Online - Zoom Meeting', 'Statewide', 'Virtual Event', 'Workshop', 'Learn about green cleaning certification programs, eco-friendly products, and how to market your sustainable cleaning services to government and educational institutions.', 'Cleaning contractors, janitorial companies', TRUE, '2025-11-12', 'https://vagreennetwork.org/workshop', 'Emily Rodriguez', 'erodriguez@vagreennetwork.org', '(804) 555-0190', 'Green certifications, eco-products, sustainable practices, marketing green services', TRUE, 'https://zoom.us/j/greenclean2025', 'upcoming'),

('Suffolk City Contract Opportunities Briefing', 'City of Suffolk Procurement', 'Local Government', '2025-11-28', '2:00 PM - 4:00 PM', '442 West Washington Street, Suffolk, VA', 'Suffolk', 'City Hall Council Chambers', 'Briefing', 'Overview of upcoming city contracts for FY2026 including facilities maintenance, custodial services, and grounds keeping. Meet department heads and procurement staff.', 'Local contractors, service providers', TRUE, '2025-11-25', 'https://suffolkva.us/procurement', 'Thomas Jackson', 'tjackson@suffolkva.us', '(757) 514-4010', 'City contracts, procurement process, small business participation, contract specifications', FALSE, NULL, 'upcoming'),

('Hampton University Vendor Registration Day', 'Hampton University Procurement', 'University', '2025-12-03', '1:00 PM - 4:00 PM', '100 E Queen Street, Hampton, VA', 'Hampton', 'Hampton University Student Center', 'Registration Event', 'Register as an approved vendor for Hampton University. Meet with procurement staff, learn about contracting process, and discover upcoming opportunities in facilities services.', 'Contractors, suppliers, service providers', TRUE, '2025-11-30', 'https://hamptonu.edu/vendor-registration', 'Michael Johnson', 'procurement@hamptonu.edu', '(757) 727-5000', 'Vendor registration, university procurement, facilities contracts, compliance requirements', FALSE, NULL, 'upcoming'),

('Tidewater Builders Association Trade Show', 'Tidewater Builders Association', 'Trade Association', '2025-12-10', '10:00 AM - 6:00 PM', '1000 N Military Highway, Norfolk, VA', 'Norfolk', 'Norfolk Scope Arena', 'Trade Show', 'Major trade show featuring construction, maintenance, and facilities services. Government procurement booth and networking opportunities with property managers and facility directors.', 'Contractors, trades, service providers', TRUE, '2025-12-05', 'https://tidewaterbuilders.org/tradeshow', 'Laura Bennett', 'lbennett@tidewaterbuilders.org', '(757) 420-2434', 'Construction services, maintenance, facilities management, commercial cleaning', FALSE, NULL, 'upcoming'),

('Chesapeake Economic Development Business Forum', 'City of Chesapeake Economic Development', 'Local Government', '2025-11-25', '8:00 AM - 12:00 PM', '307 Cedar Road, Chesapeake, VA', 'Chesapeake', 'Chesapeake Conference Center', 'Business Forum', 'Quarterly forum for local businesses to learn about city development projects, upcoming contracts, and economic development initiatives. Includes city services procurement overview.', 'Local businesses, contractors', TRUE, '2025-11-20', 'https://cityofchesapeake.net/business-forum', 'Karen Williams', 'kwilliams@cityofchesapeake.net', '(757) 382-6306', 'City projects, procurement opportunities, business resources, networking', FALSE, NULL, 'upcoming'),

('Virtual Federal Contracting 101 Webinar', 'Small Business Development Center', 'Government Program', '2025-11-19', '2:00 PM - 4:00 PM', 'Online - Teams Meeting', 'Statewide', 'Virtual Event', 'Webinar', 'Introduction to federal government contracting. Learn about SAM.gov registration, NAICS codes, set-asides, and how to find federal opportunities for cleaning and maintenance services.', 'Small businesses new to government contracting', TRUE, '2025-11-17', 'https://virginiasbdc.org/federal-101', 'James Patterson', 'jpatterson@virginiasbdc.org', '(804) 555-0145', 'Federal contracting basics, SAM.gov, certifications, bid process, small business programs', TRUE, 'https://teams.microsoft.com/federal-contracting-101', 'upcoming');
