-- ==============================================================
-- COMPLETE SUPPLY CONTRACTS MIGRATION FOR RENDER POSTGRESQL
-- Copy and paste this entire file into Render database shell
-- ==============================================================

-- 1. CREATE SUPPLY_CONTRACTS TABLE
CREATE TABLE IF NOT EXISTS supply_contracts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    agency VARCHAR(255) NOT NULL,
    location VARCHAR(100) NOT NULL,
    contract_type VARCHAR(100) DEFAULT 'Supply Contract',
    product_category VARCHAR(100) NOT NULL,
    estimated_value DECIMAL(12,2),
    contract_term VARCHAR(100),
    bid_deadline DATE NOT NULL,
    delivery_start DATE,
    posted_date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    requirements TEXT,
    product_list TEXT,
    minimum_order VARCHAR(100),
    delivery_frequency VARCHAR(100),
    website_url VARCHAR(500),
    contact_name VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    naics_code VARCHAR(20) DEFAULT '424690',
    is_quick_win BOOLEAN DEFAULT FALSE,
    is_small_business_set_aside BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) DEFAULT 'open',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_supply_contracts_location ON supply_contracts(location);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_deadline ON supply_contracts(bid_deadline);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_category ON supply_contracts(product_category);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_quick_win ON supply_contracts(is_quick_win);
CREATE INDEX IF NOT EXISTS idx_supply_contracts_status ON supply_contracts(status);

-- 3. INSERT 31 SUPPLY CONTRACT OPPORTUNITIES
-- This will insert all supply contracts if they don't already exist

INSERT INTO supply_contracts (title, agency, location, contract_type, product_category, estimated_value, contract_term, bid_deadline, delivery_start, description, requirements, product_list, minimum_order, delivery_frequency, website_url, contact_name, contact_email, contact_phone, is_quick_win, is_small_business_set_aside, status, posted_date) VALUES
('Janitorial Supplies Standing Order FY2026', 'City of Hampton', 'Hampton, VA', 'Standing Order', 'General Janitorial Supplies', 125000.00, '1 year with 4 optional renewals', '2025-11-20', '2025-12-01', 'Standing order for general janitorial supplies including cleaning chemicals, paper products, trash bags, and dispensers. Delivery as needed within 48 hours.', 'Local vendor preferred. Must provide MSDS sheets. Eco-friendly products preferred.', 'Multi-purpose cleaners, glass cleaners, disinfectants, paper towels, toilet paper, trash bags (all sizes), hand soap, dispensers', '$500 minimum order', 'As needed - 48hr delivery', 'https://www.hampton.gov/bids.aspx', 'Karen Williams', 'kwilliams@hampton.gov', '757-727-6000', TRUE, TRUE, 'open', '2025-10-21'),

('Green Cleaning Products Annual Supply', 'Hampton Public Schools', 'Hampton, VA', 'Annual Supply Contract', 'Eco-Friendly Products', 85000.00, '1 year', '2025-11-25', '2025-12-15', 'Annual supply contract for Green Seal certified cleaning products for 12 schools. Must meet EPA Safer Choice standards.', 'Green Seal or EPA Safer Choice certified products only. Local small business preference.', 'All-purpose cleaners, glass cleaners, floor cleaners, disinfectants, degreasers - all eco-friendly certified', '$300 minimum', 'Monthly bulk delivery + emergency 24hr', 'https://www.hampton.gov/schools', 'David Chen', 'dchen@hcs.k12.va.us', '757-727-2000', TRUE, TRUE, 'open', '2025-10-26'),

('Industrial Cleaning Chemicals Bulk Order', 'Newport News Shipbuilding', 'Newport News, VA', 'Bulk Supply', 'Industrial Chemicals', 450000.00, '2 years', '2025-11-30', '2026-01-15', 'Bulk supply of industrial-grade cleaning chemicals for shipyard operations. Heavy-duty degreasers, solvents, and specialized marine cleaning products.', 'Must meet OSHA and EPA regulations. Maritime industry experience required. Hazmat handling certification needed.', 'Heavy-duty degreasers, industrial solvents, rust removers, marine-grade cleaners, anti-slip coatings, paint prep chemicals', '$2000 minimum', 'Weekly scheduled + emergency same-day', 'https://www.huntingtoningalls.com/suppliers', 'Michael Thompson', 'michael.thompson@hii-nns.com', '757-380-2000', FALSE, FALSE, 'open', '2025-10-30'),

('Restroom Paper Products Annual Contract', 'City of Suffolk', 'Suffolk, VA', 'Annual Contract', 'Paper Products', 65000.00, '1 year with 2 renewals', '2025-11-22', '2025-12-10', 'Annual contract for restroom paper products for all city facilities including offices, parks, and recreational centers.', 'Bulk packaging required. Local delivery preferred. Recycled content products encouraged.', 'Toilet paper (commercial rolls), paper towels, multifold towels, seat covers, facial tissue, hand towels', '$400 minimum', 'Bi-weekly scheduled deliveries', 'https://www.suffolkva.us/bids', 'Patricia Rodriguez', 'prodriguez@suffolkva.us', '757-514-4000', TRUE, TRUE, 'open', '2025-10-23'),

('Floor Care Products Standing Order', 'Virginia Beach Public Works', 'Virginia Beach, VA', 'Standing Order', 'Floor Care', 95000.00, '18 months', '2025-11-28', '2025-12-20', 'Standing order for complete floor care program including cleaners, strippers, waxes, polishes, and equipment supplies.', 'Products compatible with existing equipment. Technical training included. Same-day emergency delivery required.', 'Floor cleaners, strippers, waxes, polishes, mop heads, microfiber pads, burnishing pads, dusting supplies', '$350 minimum', 'Monthly + emergency same-day', 'https://www.vbgov.com/business/procurement', 'James Wilson', 'jwilson@vbgov.com', '757-385-4131', TRUE, FALSE, 'open', '2025-10-28'),

('PPE & Safety Equipment Bulk Supply', 'Hampton VA Medical Center', 'Hampton, VA', 'Bulk Supply', 'PPE & Safety', 180000.00, '1 year', '2025-12-05', '2026-01-01', 'Bulk supply of personal protective equipment including gloves, masks, gowns, and safety glasses for medical facility cleaning staff.', 'FDA approved products. Medical grade quality. Must meet VA healthcare standards.', 'Nitrile gloves (all sizes), N95 masks, surgical masks, disposable gowns, safety glasses, face shields, shoe covers', '$500 minimum', 'Weekly + emergency 4hr', 'https://www.va.gov/OALC/vendors/', 'Dr. Sarah Mitchell', 'sarah.mitchell@va.gov', '757-722-9961', FALSE, TRUE, 'open', '2025-11-05'),

('Trash Bags & Liners Multi-Year Contract', 'Newport News Public Schools', 'Newport News, VA', 'Multi-Year Contract', 'Waste Management Supplies', 72000.00, '3 years', '2025-11-18', '2025-12-01', 'Three-year contract for trash bags and can liners for 35 schools and administrative buildings. Various sizes needed.', 'Bulk delivery and storage capabilities required. Local small business preference.', 'Trash bags (13gal, 30gal, 55gal), can liners (various sizes), recycling bags, biohazard bags', '$300 minimum', 'Monthly bulk delivery', 'https://www.nnschools.org/purchasing', 'Robert Martinez', 'rmartinez@nnschools.org', '757-591-4500', TRUE, TRUE, 'open', '2025-10-19'),

('Disinfectants & Sanitizers Emergency Stock', 'City of Williamsburg', 'Williamsburg, VA', 'Emergency Stock', 'Disinfectants', 45000.00, '6 months renewable', '2025-11-15', '2025-11-25', 'Emergency stockpile of EPA-registered disinfectants and sanitizers for quick response needs. Hospital-grade products required.', 'EPA List N products only. Emergency delivery within 2 hours. Small business set-aside.', 'Hospital-grade disinfectants, hand sanitizers, disinfecting wipes, surface sanitizers, fogger solutions', '$200 minimum', 'As needed - 2hr emergency delivery', 'https://www.williamsburgva.gov/business', 'Emily Thompson', 'ethompson@williamsburgva.gov', '757-220-6100', TRUE, TRUE, 'open', '2025-10-16'),

('Window Cleaning Solutions Annual Supply', 'City of Portsmouth', 'Portsmouth, VA', 'Annual Supply', 'Window Cleaning', 38000.00, '1 year', '2025-11-30', '2025-12-15', 'Annual supply of professional window cleaning solutions, squeegees, and related equipment for municipal buildings.', 'Streak-free professional grade products. Equipment compatibility required.', 'Window cleaning solutions, glass cleaners, squeegees, extension poles, microfiber cloths, water-fed pole chemicals', '$250 minimum', 'Monthly deliveries', 'https://www.portsmouthva.gov/procurement', 'Linda Carter', 'lcarter@portsmouthva.gov', '757-393-8000', TRUE, TRUE, 'open', '2025-10-31'),

('Carpet Care Products Bulk Order', 'Norfolk International Airport', 'Norfolk, VA', 'Bulk Order', 'Carpet Care', 115000.00, '2 years', '2025-12-10', '2026-01-05', 'Bulk supply of carpet cleaning chemicals, spot removers, and deodorizers for high-traffic airport facility.', '24/7 availability required. Aviation facility experience preferred. Emergency delivery capability.', 'Carpet shampoos, spot removers, deodorizers, extraction chemicals, pre-spray treatments, protectants', '$500 minimum', 'Bi-weekly + 4hr emergency', 'https://www.norfolkairport.com/about/doing-business', 'Andrew Foster', 'afoster@norfolkairport.com', '757-857-3351', FALSE, FALSE, 'open', '2025-11-10'),

('Multi-Purpose Cleaners Concentrate Program', 'Hampton Roads Transit', 'Norfolk, VA', 'Concentrate Program', 'Cleaning Chemicals', 92000.00, '1 year', '2025-11-27', '2025-12-18', 'Concentrate cleaning chemical program for bus fleet and facilities. Dilution control systems included.', 'Dilution control equipment provided. Training included. Local service required.', 'Multi-purpose concentrates, glass cleaner concentrates, degreaser concentrates, dispensing systems, training', '$400 minimum', 'Monthly + equipment maintenance', 'https://www.gohrt.com/about/procurement/', 'Marcus Johnson', 'mjohnson@gohrt.com', '757-222-6000', TRUE, FALSE, 'open', '2025-10-28'),

('Restroom Care Products Complete Program', 'Chesapeake Public Schools', 'Chesapeake, VA', 'Complete Program', 'Restroom Care', 135000.00, '2 years', '2025-12-01', '2026-01-02', 'Complete restroom care program for 48 schools including cleaners, disinfectants, air care, and paper products.', 'Program pricing required. Training provided. Local delivery and service.', 'Bowl cleaners, urinal cleaners, air fresheners, hand soaps, sanitizers, paper products, dispensers, odor control', '$600 minimum', 'Weekly scheduled deliveries', 'https://www.cpschools.com/departments/purchasing', 'Jennifer Lee', 'jlee@cpschools.com', '757-547-0153', TRUE, TRUE, 'open', '2025-11-01'),

('Food Service Cleaning Chemicals', 'Eastern Virginia Medical School', 'Norfolk, VA', 'Annual Contract', 'Food Service Chemicals', 68000.00, '1 year', '2025-11-25', '2025-12-20', 'Food service cleaning chemicals for campus dining facilities and cafeterias. NSF certified products required.', 'NSF certification required. Food-safe products only. Training included.', 'Dish detergents, sanitizers, degreasers, oven cleaners, floor cleaners (food service grade), hand soap', '$300 minimum', 'Weekly deliveries', 'https://www.evms.edu/about/administrative_offices/procurement/', 'Thomas Anderson', 'andersth@evms.edu', '757-446-5000', FALSE, TRUE, 'open', '2025-10-26'),

('Industrial Degreaser Bulk Supply', 'BAE Systems Norfolk Ship Repair', 'Norfolk, VA', 'Bulk Supply', 'Industrial Chemicals', 225000.00, '18 months', '2025-12-08', '2026-01-20', 'Heavy-duty industrial degreasers for ship repair and maintenance operations. Marine environment approved.', 'Maritime industry certified. EPA compliant. Hazmat certified delivery.', 'Heavy-duty degreasers, engine cleaners, bilge cleaners, industrial solvents, parts washers, rust inhibitors', '$1500 minimum', 'Twice weekly + emergency', 'https://www.baesystems.com/en-us/our-company/inc-businesses/maritime-services', 'Kevin Roberts', 'kevin.roberts@baesystems.com', '757-494-4000', FALSE, FALSE, 'open', '2025-11-08'),

('Green Seal Certified Complete Line', 'City of Norfolk', 'Norfolk, VA', 'Eco Program', 'Eco-Friendly Products', 158000.00, '2 years', '2025-11-22', '2025-12-15', 'Complete line of Green Seal certified cleaning products for all municipal facilities. Sustainability program.', 'Green Seal GS-37 or GS-40 certified. Carbon neutral delivery preferred. Local company priority.', 'All-purpose cleaners, glass cleaners, restroom cleaners, floor care, hand soap - all Green Seal certified', '$500 minimum', 'Bi-weekly scheduled', 'https://www.norfolk.gov/business', 'Rachel Green', 'rachel.green@norfolk.gov', '757-664-4000', TRUE, TRUE, 'open', '2025-10-22'),

('Microfiber Cleaning System Complete', 'Hampton University', 'Hampton, VA', 'System Program', 'Cleaning Equipment Supplies', 78000.00, '1 year', '2025-12-03', '2025-12-28', 'Complete microfiber cleaning system including mops, cloths, and laundering service for campus facilities.', 'Laundering service included. Color-coded system required. Training provided.', 'Microfiber mops, cloths, dusters, pads, carts, laundry service, dispensing systems', '$350 minimum', 'Weekly + laundry service', 'https://www.hamptonu.edu/administration/purchasing/', 'Melissa Wright', 'melissa.wright@hamptonu.edu', '757-727-5000', TRUE, FALSE, 'open', '2025-11-03'),

('High-Performance Floor Finish Program', 'Virginia Wesleyan University', 'Virginia Beach, VA', 'Floor Program', 'Floor Care', 52000.00, '18 months', '2025-11-20', '2025-12-10', 'High-performance floor finish program including products, equipment, and technical training for campus facilities.', 'Technical training required. Equipment compatibility. Local service support.', 'Floor finish, sealer, stripper, cleaner, burnishing pads, applicators, training materials', '$280 minimum', 'Monthly + technical support', 'https://www.vwu.edu/about/offices-services/purchasing/', 'Daniel Cooper', 'dcooper@vwu.edu', '757-455-3200', TRUE, TRUE, 'open', '2025-10-20'),

('Odor Control Solutions Hospital Grade', 'Riverside Regional Medical Center', 'Newport News, VA', 'Hospital Program', 'Odor Control', 85000.00, '1 year', '2025-12-05', '2026-01-01', 'Hospital-grade odor control program including enzymatic cleaners, air care, and specialized products.', 'Hospital approved products. Hypoallergenic. Medical facility experience required.', 'Enzymatic cleaners, odor neutralizers, air care systems, drain treatments, waste receptacle treatments', '$400 minimum', 'Weekly + emergency 2hr', 'https://www.riversideonline.com/about/vendors', 'Dr. Patricia Hayes', 'phayes@rivhs.com', '757-594-2000', FALSE, TRUE, 'open', '2025-11-05'),

('All-Purpose Cleaner Concentrate Bulk', 'City of Virginia Beach', 'Virginia Beach, VA', 'Bulk Concentrate', 'Cleaning Chemicals', 195000.00, '2 years', '2025-11-30', '2026-01-10', 'Bulk concentrate all-purpose cleaners for city-wide facilities. Dilution control system included.', 'City-wide program. Training required. Local service and support mandatory.', 'Multi-surface concentrates, glass concentrates, disinfectant concentrates, dilution systems, training', '$800 minimum', 'Monthly + equipment service', 'https://www.vbgov.com/business/procurement', 'Christopher Davis', 'cdavis@vbgov.com', '757-385-4131', TRUE, FALSE, 'open', '2025-10-30'),

('Paper Towel & Tissue Emergency Stock', 'Suffolk Public Schools', 'Suffolk, VA', 'Emergency Stock', 'Paper Products', 48000.00, '6 months', '2025-11-18', '2025-12-01', 'Emergency stockpile of paper towels and tissue products with rapid replenishment capability.', 'Emergency 24-hour delivery required. Storage provided by district. Small business priority.', 'Paper towels (roll and fold), toilet tissue, facial tissue, napkins, industrial wipes', '$250 minimum', 'As needed - 24hr delivery', 'https://www.spsk12.net/departments/purchasing', 'Maria Santos', 'msantos@spsk12.net', '757-925-5682', TRUE, TRUE, 'open', '2025-10-19'),

('Hospital-Grade Disinfectant Program', 'Sentara Norfolk General Hospital', 'Norfolk, VA', 'Hospital Program', 'Disinfectants', 320000.00, '1 year', '2025-12-10', '2026-01-05', 'Complete hospital-grade disinfection program including EPA List N products, training, and compliance support.', 'Healthcare facility certification required. EPA registered products. Training and audits included.', 'Hospital disinfectants, TB disinfectants, sporicidal cleaners, surface disinfectants, hand sanitizers, wipes', '$1000 minimum', 'Twice weekly + emergency 2hr', 'https://www.sentara.com/about/vendor-information', 'Dr. Elizabeth Moore', 'elmoore@sentara.com', '757-388-3000', FALSE, FALSE, 'open', '2025-11-10'),

('Specialty Cleaning Chemicals Marine', 'Colonna''s Shipyard', 'Norfolk, VA', 'Marine Specialty', 'Marine Chemicals', 142000.00, '1 year', '2025-11-28', '2025-12-20', 'Specialized marine-grade cleaning chemicals for yacht and vessel servicing. Premium products required.', 'Marine industry experience required. Premium brands. Technical support included.', 'Marine cleaners, teak cleaners, hull cleaners, metal polishes, anti-fouling treatments, bilge cleaners', '$600 minimum', 'Weekly + emergency same-day', 'https://www.colonnashipyard.com/services', 'William Colonna', 'bill@colonnashipyard.com', '757-627-2555', FALSE, FALSE, 'open', '2025-10-28'),

('Environmentally Preferable Products', 'Hampton Roads Sanitation District', 'Virginia Beach, VA', 'Green Program', 'Eco-Friendly Products', 110000.00, '2 years', '2025-12-01', '2026-01-02', 'Environmentally preferable cleaning products meeting EPA Safer Choice and Green Seal standards.', 'Third-party certified only. Sustainability reporting required. Carbon neutral delivery preferred.', 'EPA Safer Choice cleaners, Green Seal products, biodegradable degreasers, plant-based solutions', '$450 minimum', 'Bi-weekly deliveries', 'https://www.hrsd.com/procurement', 'Sandra Williams', 'swilliams@hrsd.com', '757-460-7000', TRUE, TRUE, 'open', '2025-11-01'),

('Restroom Air Care System Complete', 'Newport News/Williamsburg Airport', 'Newport News, VA', 'Air Care System', 'Air Care', 62000.00, '18 months', '2025-11-25', '2025-12-18', 'Complete automated air care system for airport restrooms. Automated dispensing and monitoring.', 'Automated system required. Remote monitoring capability. 24/7 service support.', 'Automated air fresheners, refills, odor control systems, monitoring equipment, service program', '$320 minimum', 'Monthly + equipment service', 'https://www.flyphf.com/business-opportunities', 'Gregory Martinez', 'gmartinez@flyphf.com', '757-877-0221', FALSE, FALSE, 'open', '2025-10-26'),

('Hand Hygiene Program Hospital Wide', 'Bon Secours Mary Immaculate Hospital', 'Newport News, VA', 'Hygiene Program', 'Hand Hygiene', 98000.00, '1 year', '2025-12-08', '2026-01-01', 'Hospital-wide hand hygiene program including soap, sanitizers, and dispensing systems with compliance monitoring.', 'Healthcare facility approved. Hypoallergenic required. Compliance monitoring included.', 'Hand soap, hand sanitizers, foam soap, lotion, dispensers, monitoring systems, training materials', '$400 minimum', 'Weekly + emergency 4hr', 'https://www.bonsecours.com/hampton-roads/for-vendors', 'Nursing Administrator', 'supplier@bshsi.org', '757-886-6000', FALSE, TRUE, 'open', '2025-11-08'),

('Floor Sealer & Finish Bulk Supply', 'College of William & Mary', 'Williamsburg, VA', 'Bulk Supply', 'Floor Care', 72000.00, '1 year', '2025-11-22', '2025-12-15', 'Bulk supply of commercial floor sealer and finish for historic campus buildings. Premium products required.', 'Historic building compatible. VOC compliant. Technical training included.', 'Floor sealer, floor finish, stripper, cleaner, burnishing chemicals, applicators', '$350 minimum', 'Monthly + technical support', 'https://www.wm.edu/offices/procurement/', 'Facilities Director', 'procurement@wm.edu', '757-221-4000', TRUE, FALSE, 'open', '2025-10-22'),

('Kitchen & Food Prep Sanitizers', 'Christopher Newport University', 'Newport News, VA', 'Food Service', 'Food Service Chemicals', 55000.00, '1 year', '2025-11-20', '2025-12-10', 'Food service sanitizers and cleaners for university dining facilities. NSF certified products required.', 'NSF certification mandatory. Food-contact safe. Health department approved.', 'Quaternary sanitizers, food-contact cleaners, dishwashing chemicals, hand soap, floor cleaners', '$280 minimum', 'Weekly deliveries', 'https://cnu.edu/purchasing/', 'Dining Services Manager', 'dining@cnu.edu', '757-594-7000', TRUE, TRUE, 'open', '2025-10-20'),

('Heavy-Duty Degreaser Industrial', 'Huntington Ingalls Industries', 'Newport News, VA', 'Industrial Supply', 'Industrial Chemicals', 385000.00, '2 years', '2025-12-12', '2026-01-25', 'Heavy-duty industrial degreasers for aircraft carrier construction and nuclear ship work. High-performance formulas.', 'Nuclear facility approved. Security clearance for delivery. Maritime certified products.', 'Aircraft carrier degreasers, nuclear-grade cleaners, heavy machinery degreasers, parts washers', '$2500 minimum', 'Twice weekly + emergency', 'https://www.huntingtoningalls.com/suppliers', 'Procurement Manager', 'suppliers@hii-nns.com', '757-380-2000', FALSE, FALSE, 'open', '2025-11-12'),

('Biohazard & Medical Waste Cleaners', 'Eastern Shore Rural Health', 'Norfolk, VA', 'Medical Specialty', 'Specialty Chemicals', 42000.00, '1 year', '2025-11-27', '2025-12-18', 'Specialized cleaners for biohazard and medical waste areas. EPA registered tuberculocidal required.', 'Bloodborne pathogen rated. OSHA compliant. Healthcare facility certified.', 'Biohazard cleaners, TB disinfectants, sharps container cleaners, blood spill kits, decontamination supplies', '$220 minimum', 'Bi-weekly + emergency 4hr', 'https://esrh.org/about/vendors', 'Safety Coordinator', 'safety@esrh.org', '757-442-8700', TRUE, TRUE, 'open', '2025-10-27'),

('Glass & Surface Cleaner Concentrate', 'Town of Smithfield', 'Smithfield, VA', 'Annual Supply', 'Cleaning Chemicals', 28000.00, '1 year', '2025-11-18', '2025-12-01', 'Concentrated glass and surface cleaners for municipal buildings and fleet vehicles.', 'Streak-free performance. Dilution control preferred. Local supplier priority.', 'Glass cleaner concentrate, multi-surface cleaner, stainless steel cleaner, dispensing equipment', '$180 minimum', 'Monthly deliveries', 'https://www.smithfieldva.gov/departments/purchasing', 'Town Manager Office', 'townhall@smithfieldva.gov', '757-365-4200', TRUE, TRUE, 'open', '2025-10-19'),

('Carpet Extraction Chemicals Program', 'Hampton Roads Convention Center', 'Hampton, VA', 'Extraction Program', 'Carpet Care', 88000.00, '18 months', '2025-12-05', '2025-12-28', 'Complete carpet extraction program for convention center including chemicals, equipment, and emergency response.', 'Event-ready response. Emergency 2-hour availability. Technical training provided.', 'Extraction chemicals, pre-sprays, spot removers, deodorizers, protectants, traffic lane cleaners', '$400 minimum', 'Weekly + 2hr emergency', 'https://www.hamptoncc.com/planners/event-services/', 'Operations Manager', 'operations@hamptoncc.com', '757-727-1271', FALSE, FALSE, 'open', '2025-11-05');

-- 4. VERIFY INSERTION
SELECT COUNT(*) as total_supply_contracts FROM supply_contracts;
SELECT product_category, COUNT(*) as count FROM supply_contracts GROUP BY product_category ORDER BY count DESC;

-- Done! You should see 31 supply contracts across multiple categories.
